-- 코드를 입력하세요
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'MILK'
INTERSECT
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME = 'YOGURT'
ORDER BY CART_ID ;

/*
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Milk', 'Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) >= 2   # DISTINCT : 요거트 요거트 인 경우
ORDER BY CART_ID ;
*/