-- 코드를 작성해주세요
SELECT ID
FROM ECOLI_DATA 
WHERE PARENT_ID IN (SELECT ID
                   FROM ECOLI_DATA
                   WHERE PARENT_ID IN (SELECT ID
                                      FROM ECOLI_DATA
                                      WHERE PARENT_ID IS NULL)) 
ORDER BY ID ;

/*
WITH RECURSIVE A AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
UNION ALL
    SELECT E.ID, E.PARENT_ID, A.GENERATION + 1
    FROM ECOLI_DATA E
    INNER JOIN A ON E.PARENT_ID = A.ID
)

SELECT ID
FROM A
WHERE GENERATION = 3 
ORDER BY 1 ;
*/