-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, 
MONTH(SALES_DATE) AS MONTH, 
COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS, 
ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PURCHASED_RATIO
FROM USER_INFO U JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE JOINED LIKE '2021%'
GROUP BY 1, 2
ORDER BY 1, 2 ;