-- 코드를 입력하세요
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.DATETIME IS NULL
ORDER BY I.DATETIME
LIMIT 3 ;

/*
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATETIME
LIMIT 3 ;


SELECT NAME, DATETIME
FROM ANIMAL_INS I
WHERE NOT EXISTS (SELECT ANIMAL_ID FROM ANIMAL_OUTS O WHERE I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY DATETIME
LIMIT 3 ;
*/