-- 코드를 입력하세요
WITH A AS (
    SELECT C.DAILY_FEE, C.CAR_TYPE, H.HISTORY_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
    (CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE 'NONE'
    END) AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C
    INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭')
    
    
    
SELECT A.HISTORY_ID, ROUND(A.DAILY_FEE * A.PERIOD * (100-IFNULL(P.DISCOUNT_RATE, 0))*0.01) AS FEE
FROM A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.DURATION_TYPE = A.DURATION_TYPE AND P.CAR_TYPE = A.CAR_TYPE
ORDER BY 2 DESC, 1 DESC ;



/*
DATE_ADD, DATE_SUB : (기준날짜, INTERVAL)
DATEDIFF : 두 기간 일수 계산
TIMEDIFF : 두 기간 시간 계산

REGEXP_REPLACE(DURATION_TYPE, '[^0-9]+', '') : 문자열에서 숫자만 추출
REGEXP_REPLACE(DURATION_TYPE, '[0-9]+', '') : 문자열에서 숫자뺀 문자만 추출
*/