-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, P.PT_NO, D.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT P LEFT JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO
RIGHT JOIN DOCTOR D ON A.MDDR_ID = D.DR_ID

WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
AND APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD ;