-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_DEPARTMENT D JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
    JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
WHERE YEAR = '2022'
GROUP BY G.EMP_NO
ORDER BY 1 DESC
LIMIT 1 ;