-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (SELECT CATEGORY, MAX(PRICE) 
                            FROM FOOD_PRODUCT 
                            WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
                            GROUP BY CATEGORY)
ORDER BY MAX_PRICE DESC ;

/*
SELECT 절에 MAX 취하면 첫번째 행만 가져옴 -> 오류
WITH A AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
    GROUP BY CATEGORY
    ORDER BY PRICE DESC
    )
SELECT * FROM A ;
*/